language: node_js
node_js:
- '0.12'
env:
  global:
  - GH_REF=github.com/mxabierto/procurement-analytics.git
  - DEPLOY_BRANCH=master
  - secure: oYNPRhNoi+LMMU5KuhGUusFpg5PJuTYl0L5tFqt7eenz3mQTq3+Ne2gMnhV3POuTuoHBYz6yU8UrLiqbROKOigU2WEZCCo0TL11aSGY8sxThdr2mw1NBjZ3zGIemXbuOgb00m+ebsycy83pr1A4RbLO706Fz9D8an/DMy59ma9L5OrnsE8ouN25MdNMG4ohQMhzg71CfriFEJNaXnf1h0gz4IJQ9eakSh06YWs/JIs7+jxI1MdLNMdKd/Iz/KC6gzgbbYEReV6gEPbS4YcdvWFwnwRpNBweYfjqQSWxTs5yow0uFlnopZFGRuzAxvYJ7BAvLNPOjeVSkPUi4u+FOMShDzGvwvh/4KD77EJTujV6UxxCLGCtKOF0iP89Ucq4xguhN4M0GP5LwNRF3DaVAOfs7ZizVJLztnMYboAfIGNLOnJCsui0EpKpOtmmh6zxp1jQCE5H54yfiO1yHX1IW0dfvgCblZXNqC6g6d4nVfRBwQTGZnirR7tG1nnUf4pVy2RDAHdB0m5Cxgq7R9+u1WUv9UHrCxW/nydunXF0SduBs1Wfz+e3ue6d3nP978ansz5hQm6zXiS7eUsxIIAPDo2fpqVRZO7HvJnJuZdXsI49+508FB/TCFBwKXfaPKU6FelsZ7mcWzNzLaTNoH17UTCnbf4ENHzCdDZ6zm/LihLQ=
before_install:
- chmod +x ./.build_scripts/deploy.sh
script:
- gulp prod
after_success:
- "./.build_scripts/deploy.sh"
